# jjongpal-app 프로젝트 그래들 설정
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# 그래들 데몬 10분 후 종료
org.gradle.daemon.idletimeout=600000

# JDK 21 강제 (안드로이드 그래들 플러그인 9+ 가 요구)
org.gradle.java.home=/home/weplay/opt/jdk-21.0.5+11
